objects/MarketingCampaigns__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Marketing Campaigns</label>
</CustomObject>

classes/CampanasMarketingEdit.cls
public class CampanasMarketingEdit {

    public List<MarketingCampaigns__c> settingLst {get; set;}
    
    public CampanasMarketingEdit() {
       
            settingLst = [SELECT Id, Name, Active__c, Origin__c FROM MarketingCampaigns__c ORDER BY Name];
        
        }
  
    
    public PageReference save() {
        upsert settingLst;
        PageReference pr = Page.campanasmarketinglist;
        return pr;
        
    }
    
     public PageReference Nueva() {
        // MarketingCampaigns__c newCampaign = new MarketingCampaigns__c();
        // settingLst.add(newCampaign);     
        
        PageReference pr = Page.campanasmarketing;
        return pr;
        
    }


}